import React, { useRef, useState } from 'react';
import { Animated, PanResponder, Pressable, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Screen, TopBar, PrimaryButton, ProgressBar } from '@/components/StudyUI';
import { useColors } from '@/hooks/useColors';

const cards = [{ front: 'What is the goal of cellular respiration?', back: 'To convert energy in glucose into ATP, the cell’s immediately usable energy.' }, { front: 'Where does glycolysis happen?', back: 'In the cytoplasm. It splits glucose into two smaller molecules.' }, { front: 'What enters the Krebs cycle?', back: 'Acetyl-CoA, produced from pyruvate after glycolysis.' }];
export default function FlashcardsScreen() { const colors = useColors(); const router = useRouter(); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [done, setDone] = useState(false); const pan = useRef(new Animated.ValueXY()).current; const next = () => { Haptics.selectionAsync(); if (index === cards.length - 1) setDone(true); else { setIndex(index + 1); setRevealed(false); } }; const responder = useRef(PanResponder.create({ onMoveShouldSetPanResponder: (_, g) => Math.abs(g.dx) > 12, onPanResponderMove: (_, g) => pan.setValue({ x: g.dx, y: 0 }), onPanResponderRelease: (_, g) => { if (Math.abs(g.dx) > 70) next(); Animated.spring(pan, { toValue: { x: 0, y: 0 }, useNativeDriver: true }).start(); } })).current; if (done) return <Screen><TopBar title="Review complete" subtitle="A SMALL WIN" onBack={() => router.back()} /><View style={styles.complete}><View style={[styles.completeIcon, { backgroundColor: colors.secondary }]}><Ionicons name="checkmark" size={34} color={colors.accent} /></View><Text style={[styles.completeTitle, { color: colors.foreground }]}>That’s a solid loop.</Text><Text style={[styles.completeText, { color: colors.mutedForeground }]}>You reviewed {cards.length} cards. Give your memory a little space, then come back tomorrow.</Text><PrimaryButton label="Back to library" onPress={() => router.back()} icon="arrow-back" /></View></Screen>; return <Screen scroll={false}><TopBar title="Flashcards" subtitle={`CELLULAR RESPIRATION · ${index + 1}/${cards.length}`} onBack={() => router.back()} /><View style={styles.progress}><ProgressBar value={(index + 1) / cards.length} color={colors.primary} /></View><Text style={[styles.hint, { color: colors.mutedForeground }]}>{revealed ? 'THE ANSWER' : 'TAP TO REVEAL'}</Text><Animated.View {...responder.panHandlers} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border, transform: [{ translateX: pan.x }] }]}><Pressable onPress={() => { Haptics.selectionAsync(); setRevealed(!revealed); }} style={styles.cardPress}><Ionicons name={revealed ? 'checkmark-circle-outline' : 'layers-outline'} size={26} color={revealed ? colors.accent : colors.primary} /><Text style={[styles.cardText, { color: colors.foreground }]}>{revealed ? cards[index].back : cards[index].front}</Text><Text style={[styles.tap, { color: colors.mutedForeground }]}>{revealed ? 'Tap to see the question' : 'Tap anywhere on the card'}</Text></Pressable></Animated.View><View style={styles.bottom}><Text style={[styles.swipe, { color: colors.mutedForeground }]}>Swipe left when you’ve got it</Text><PrimaryButton label={revealed ? 'Next card' : 'Reveal answer'} onPress={() => revealed ? next() : setRevealed(true)} icon={revealed ? 'arrow-forward' : 'eye-outline'} /></View></Screen>; }
const styles = StyleSheet.create({ progress: { marginTop: 5 }, hint: { fontFamily: 'Inter_700Bold', letterSpacing: 1.3, fontSize: 10, textAlign: 'center', marginTop: 36 }, card: { height: 310, borderRadius: 25, borderWidth: 1, marginTop: 12, overflow: 'hidden' }, cardPress: { flex: 1, padding: 27, justifyContent: 'center', alignItems: 'center', gap: 18 }, cardText: { fontFamily: 'Inter_600SemiBold', fontSize: 22, lineHeight: 30, textAlign: 'center' }, tap: { fontFamily: 'Inter_400Regular', fontSize: 11, position: 'absolute', bottom: 20 }, bottom: { marginTop: 'auto', gap: 14, paddingBottom: 8 }, swipe: { textAlign: 'center', fontFamily: 'Inter_400Regular', fontSize: 12 }, complete: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 80, gap: 14 }, completeIcon: { width: 74, height: 74, borderRadius: 25, alignItems: 'center', justifyContent: 'center' }, completeTitle: { fontFamily: 'Inter_700Bold', fontSize: 25, marginTop: 10 }, completeText: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21, textAlign: 'center', maxWidth: 300, marginBottom: 14 } });
