import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen, ProgressBar, SectionTitle, Surface } from '@/components/StudyUI';
import { useColors } from '@/hooks/useColors';

export default function HomeScreen() {
  const colors = useColors();
  const router = useRouter();
  return <Screen>
    <View style={styles.header}><View><Text style={[styles.kicker, { color: colors.accent }]}>MONDAY, 14 OCTOBER</Text><Text style={[styles.greeting, { color: colors.foreground }]}>Good morning, Maya</Text><Text style={[styles.subtle, { color: colors.mutedForeground }]}>A small, focused session goes a long way.</Text></View><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontFamily: 'Inter_700Bold' }}>M</Text></View></View>
    <Surface style={styles.focusCard} accent><View style={styles.focusTop}><View><Text style={[styles.kicker, { color: colors.primary }]}>TODAY'S FOCUS</Text><Text style={[styles.focusTitle, { color: colors.foreground }]}>Cellular respiration</Text><Text style={[styles.subtle, { color: colors.mutedForeground }]}>Biology · 25 min deep dive</Text></View><View style={[styles.focusIcon, { backgroundColor: colors.secondary }]}><Ionicons name="leaf-outline" size={24} color={colors.accent} /></View></View><View style={styles.focusBottom}><ProgressBar value={0.62} color={colors.primary} /><Text style={[styles.percent, { color: colors.primary }]}>62%</Text></View><Pressable onPress={() => router.push('/quiz')} style={[styles.focusButton, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontFamily: 'Inter_700Bold' }}>Continue session</Text><Ionicons name="arrow-forward" size={17} color={colors.primaryForeground} /></Pressable></Surface>
    <View style={styles.stats}><Surface style={styles.stat}><Text style={[styles.statNumber, { color: colors.primary }]}>07</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>day streak</Text><View style={styles.statRow}><Ionicons name="flame" size={15} color={colors.primary} /><Text style={[styles.statNote, { color: colors.foreground }]}>Personal best</Text></View></Surface><Surface style={styles.stat}><Text style={[styles.statNumber, { color: colors.accent }]}>4.2</Text><Text style={[styles.statLabel, { color: colors.mutedForeground }]}>hours this week</Text><View style={styles.statRow}><Ionicons name="trending-up" size={15} color={colors.accent} /><Text style={[styles.statNote, { color: colors.foreground }]}>+38% from last week</Text></View></Surface></View>
    <SectionTitle title="Quick actions" />
    <View style={styles.actions}><Pressable onPress={() => router.push('/study-plan')} style={[styles.action, { backgroundColor: colors.secondary }]}><Ionicons name="calendar-outline" size={22} color={colors.primary} /><Text style={[styles.actionText, { color: colors.foreground }]}>Build a plan</Text><Text style={[styles.actionSub, { color: colors.mutedForeground }]}>Shape your week</Text></Pressable><Pressable onPress={() => router.push('/flashcards')} style={[styles.action, { backgroundColor: colors.secondary }]}><Ionicons name="layers-outline" size={22} color={colors.accent} /><Text style={[styles.actionText, { color: colors.foreground }]}>Review cards</Text><Text style={[styles.actionSub, { color: colors.mutedForeground }]}>12 waiting for you</Text></Pressable></View>
    <SectionTitle title="Recent activity" action="View progress" onAction={() => router.push('/progress')} />
    <Surface><Activity icon="checkmark-circle" title="Photosynthesis quiz" detail="8 / 10 correct · 12 min ago" color={colors.accent} /><Activity icon="document-text-outline" title="Lecture notes added" detail="Biology · 24 pages · Yesterday" color={colors.primary} /><Activity icon="chatbubble-ellipses-outline" title="Tutor conversation" detail="Organic chemistry · Yesterday" color={colors.accent} /></Surface>
  </Screen>;
}
function Activity({ icon, title, detail, color }: { icon: any; title: string; detail: string; color: string }) { const colors = useColors(); return <View style={styles.activity}><View style={[styles.activityIcon, { backgroundColor: colors.secondary }]}><Ionicons name={icon} size={18} color={color} /></View><View style={{ flex: 1 }}><Text style={[styles.actionText, { color: colors.foreground }]}>{title}</Text><Text style={[styles.actionSub, { color: colors.mutedForeground }]}>{detail}</Text></View><Ionicons name="chevron-forward" size={17} color={colors.mutedForeground} /></View>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.3, marginBottom: 6 }, greeting: { fontFamily: 'Inter_700Bold', fontSize: 25, letterSpacing: -0.7 }, subtle: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: 4 }, avatar: { width: 44, height: 44, borderRadius: 16, justifyContent: 'center', alignItems: 'center' }, focusCard: { padding: 18, marginBottom: 14 }, focusTop: { flexDirection: 'row', justifyContent: 'space-between' }, focusTitle: { fontFamily: 'Inter_700Bold', fontSize: 20, marginTop: 5 }, focusIcon: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, focusBottom: { flexDirection: 'row', gap: 10, alignItems: 'center', marginTop: 20 }, percent: { fontFamily: 'Inter_700Bold', fontSize: 12 }, focusButton: { marginTop: 18, height: 44, borderRadius: 13, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, stats: { flexDirection: 'row', gap: 10, marginBottom: 25 }, stat: { flex: 1, padding: 14 }, statNumber: { fontFamily: 'Inter_700Bold', fontSize: 28 }, statLabel: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 1 }, statRow: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: 14 }, statNote: { fontFamily: 'Inter_500Medium', fontSize: 10 }, actions: { flexDirection: 'row', gap: 10, marginBottom: 25 }, action: { flex: 1, padding: 15, borderRadius: 18 }, actionText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, actionSub: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, activity: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(142,164,192,0.14)' }, activityIcon: { width: 36, height: 36, borderRadius: 12, justifyContent: 'center', alignItems: 'center' } });