import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen, SectionTitle, Surface, ProgressBar } from '@/components/StudyUI';
import { useColors } from '@/hooks/useColors';

const bars = [{ day: 'M', value: 0.72 }, { day: 'T', value: 0.48 }, { day: 'W', value: 0.9 }, { day: 'T', value: 0.63 }, { day: 'F', value: 0.42 }, { day: 'S', value: 0.82 }, { day: 'S', value: 0.25 }];
export default function ProgressScreen() { const colors = useColors(); return <Screen><Text style={[styles.kicker, { color: colors.accent }]}>YOUR MOMENTUM</Text><Text style={[styles.title, { color: colors.foreground }]}>Progress</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Consistency is the quiet advantage.</Text><Surface style={styles.hero} accent><View><Text style={[styles.heroValue, { color: colors.primary }]}>4h 12m</Text><Text style={[styles.detail, { color: colors.mutedForeground }]}>studied this week</Text></View><View style={styles.heroRight}><Ionicons name="trending-up" size={17} color={colors.accent} /><Text style={[styles.trend, { color: colors.accent }]}>+38%</Text><Text style={[styles.detail, { color: colors.mutedForeground }]}>vs last week</Text></View></Surface><SectionTitle title="Study rhythm" action="This week" /><Surface><View style={styles.chart}>{bars.map((bar, i) => <View key={`${bar.day}-${i}`} style={styles.barGroup}><View style={[styles.barTrack, { backgroundColor: colors.muted }]}><View style={[styles.bar, { backgroundColor: i === 2 ? colors.primary : colors.accent, height: `${bar.value * 100}%` }]} /></View><Text style={[styles.day, { color: colors.mutedForeground }]}>{bar.day}</Text></View>)}</View><View style={[styles.chartLegend, { borderTopColor: colors.border }]}><Text style={[styles.detail, { color: colors.mutedForeground }]}>Deep work target</Text><Text style={[styles.detail, { color: colors.foreground }]}>5h / 6h</Text></View></Surface><SectionTitle title="Quiz performance" /><Surface><View style={styles.scoreRow}><View><Text style={[styles.score, { color: colors.foreground }]}>84%</Text><Text style={[styles.detail, { color: colors.mutedForeground }]}>average score · 6 quizzes</Text></View><View style={[styles.scoreRing, { borderColor: colors.accent }]}><Ionicons name="checkmark" size={24} color={colors.accent} /></View></View><ProgressBar value={0.84} color={colors.accent} /></Surface><SectionTitle title="A note from your tutor" /><Surface style={styles.insight}><Ionicons name="sparkles-outline" size={22} color={colors.primary} /><Text style={[styles.insightText, { color: colors.foreground }]}>You learn best when you return the next day. Keep your streak gentle: one honest 20-minute session is enough.</Text></Surface></Screen>; }
const styles = StyleSheet.create({ kicker: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.3 }, title: { fontFamily: 'Inter_700Bold', fontSize: 28, letterSpacing: -0.7, marginTop: 4 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 14, marginTop: 4, marginBottom: 22 }, hero: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 25 }, heroValue: { fontFamily: 'Inter_700Bold', fontSize: 34, letterSpacing: -1 }, heroRight: { alignItems: 'flex-end' }, trend: { fontFamily: 'Inter_700Bold', fontSize: 15 }, detail: { fontFamily: 'Inter_400Regular', fontSize: 12, marginTop: 3 }, chart: { height: 155, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', paddingTop: 8 }, barGroup: { height: '100%', alignItems: 'center', justifyContent: 'flex-end', gap: 7 }, barTrack: { width: 23, height: 125, borderRadius: 10, justifyContent: 'flex-end', overflow: 'hidden' }, bar: { width: '100%', borderRadius: 10 }, day: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, chartLegend: { marginTop: 15, paddingTop: 12, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between' }, scoreRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 }, score: { fontFamily: 'Inter_700Bold', fontSize: 31 }, scoreRing: { width: 52, height: 52, borderRadius: 26, borderWidth: 3, alignItems: 'center', justifyContent: 'center' }, insight: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' }, insightText: { flex: 1, fontFamily: 'Inter_500Medium', fontSize: 14, lineHeight: 21 } });
