import React, { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';
import { Ionicons } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { Screen, TopBar } from '@/components/StudyUI';

type Message = { id: string; role: 'user' | 'tutor'; text: string };
const starter: Message[] = [{ id: '1', role: 'tutor', text: 'Hi Maya. I’m ready when you are. What are you working through today?' }, { id: '2', role: 'user', text: 'Can you help me understand cellular respiration?' }, { id: '3', role: 'tutor', text: 'Absolutely. Think of it as a cell turning food into a usable energy currency. Want the three stages in a simple story, or a quick comparison table?' }];
const prompts = ['Explain it simply', 'Quiz me on this', 'Make a study plan'];

export default function TutorScreen() {
  const colors = useColors(); const [messages, setMessages] = useState<Message[]>(starter); const [draft, setDraft] = useState(''); const [typing, setTyping] = useState(false);
  useEffect(() => { AsyncStorage.getItem('study-companion/chat').then(raw => raw && setMessages(JSON.parse(raw) as Message[])); }, []);
  const send = (text = draft) => { const value = text.trim(); if (!value || typing) return; Haptics.selectionAsync(); const next = [...messages, { id: Date.now().toString(), role: 'user' as const, text: value }]; setMessages(next); setDraft(''); setTyping(true); setTimeout(() => { const reply: Message = { id: `${Date.now()}-reply`, role: 'tutor', text: 'Let’s make that manageable: start with the big idea, connect one example, then test your recall. I can turn this into a short quiz whenever you’re ready.' }; const complete = [...next, reply]; setMessages(complete); setTyping(false); AsyncStorage.setItem('study-companion/chat', JSON.stringify(complete)); }, 850); };
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.background }} behavior="padding"><Screen scroll={false}><TopBar title="Tutor" subtitle="YOUR POCKET TUTOR" action={() => setMessages(starter)} actionIcon="refresh-outline" /><FlatList data={[...messages].reverse()} inverted keyExtractor={item => item.id} contentContainerStyle={styles.list} showsVerticalScrollIndicator={false} renderItem={({ item }) => <View style={[styles.bubble, { backgroundColor: item.role === 'user' ? colors.primary : colors.card, alignSelf: item.role === 'user' ? 'flex-end' : 'flex-start', borderColor: colors.border }]}><Text style={[styles.bubbleText, { color: item.role === 'user' ? colors.primaryForeground : colors.foreground }]}>{item.text}</Text></View>} ListHeaderComponent={typing ? <View style={[styles.typing, { backgroundColor: colors.card }]}><ActivityIndicator size="small" color={colors.accent} /><Text style={[styles.typingText, { color: colors.mutedForeground }]}>Tutor is thinking</Text></View> : null} /><View style={styles.promptRow}>{prompts.map(prompt => <Pressable key={prompt} onPress={() => send(prompt)} style={[styles.prompt, { borderColor: colors.border }]}><Text style={[styles.promptText, { color: colors.accent }]}>{prompt}</Text></Pressable>)}</View><View style={[styles.composer, { borderColor: colors.border, backgroundColor: colors.card }]}><TextInput value={draft} onChangeText={setDraft} placeholder="Ask anything about your studies" placeholderTextColor={colors.mutedForeground} style={[styles.input, { color: colors.foreground }]} multiline /><Pressable accessibilityLabel="Send message" onPress={() => send()} style={[styles.send, { backgroundColor: draft.trim() ? colors.primary : colors.muted }]}><Ionicons name="arrow-up" size={19} color={draft.trim() ? colors.primaryForeground : colors.mutedForeground} /></Pressable></View></Screen></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ list: { paddingTop: 10, paddingBottom: 16 }, bubble: { maxWidth: '86%', borderWidth: 1, borderRadius: 18, padding: 14, marginVertical: 6 }, bubbleText: { fontFamily: 'Inter_400Regular', fontSize: 15, lineHeight: 22 }, typing: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 9, padding: 12, borderRadius: 15, marginBottom: 8 }, typingText: { fontFamily: 'Inter_500Medium', fontSize: 12 }, promptRow: { flexDirection: 'row', gap: 7, marginBottom: 10 }, prompt: { borderWidth: 1, borderRadius: 20, paddingVertical: 8, paddingHorizontal: 10 }, promptText: { fontFamily: 'Inter_500Medium', fontSize: 11 }, composer: { minHeight: 56, borderWidth: 1, borderRadius: 18, flexDirection: 'row', alignItems: 'center', paddingLeft: 14, paddingRight: 7, marginBottom: 8 }, input: { flex: 1, fontFamily: 'Inter_400Regular', fontSize: 14, maxHeight: 80, paddingVertical: 9 }, send: { width: 39, height: 39, borderRadius: 13, alignItems: 'center', justifyContent: 'center' } });